# Generated by Django 6.1.1 on 2026-09-13 17:47

import django.db.models.deletion
import gifts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guests', '0001_initial'),
        ('invitations', '0001_initial'),
        ('weddings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accept_monetary_gift', models.BooleanField(default=True)),
                ('accept_physical_gift', models.BooleanField(default=True)),
                ('allow_no_gift', models.BooleanField(default=True)),
                ('kbzpay_enabled', models.BooleanField(default=False)),
                ('kbzpay_account_name', models.CharField(blank=True, max_length=120)),
                ('kbzpay_qr', models.FileField(blank=True, upload_to=gifts.models.gift_qr_upload_to)),
                ('ayapay_enabled', models.BooleanField(default=False)),
                ('ayapay_account_name', models.CharField(blank=True, max_length=120)),
                ('ayapay_qr', models.FileField(blank=True, upload_to=gifts.models.gift_qr_upload_to)),
                ('return_gift_mode', models.CharField(choices=[('NONE', 'No return gift'), ('PER_INVITATION', 'One per invitation'), ('PER_ATTENDEE', 'One per checked-in guest'), ('CUSTOM', 'Custom quantity')], default='PER_INVITATION', max_length=24)),
                ('return_gift_name', models.CharField(blank=True, max_length=120)),
                ('return_gift_stock', models.PositiveIntegerField(default=0)),
                ('custom_return_gift_quantity', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wedding', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gift_settings', to='weddings.wedding')),
            ],
        ),
        migrations.CreateModel(
            name='GuestGiftDeclaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gift_choice', models.CharField(choices=[('NONE', 'No gift'), ('DIGITAL', 'Digital gift'), ('PHYSICAL', 'Physical gift')], default='NONE', max_length=16)),
                ('payment_method', models.CharField(choices=[('NONE', 'Not applicable'), ('KBZPAY', 'KBZPay'), ('AYAPAY', 'AYA Pay'), ('OTHER', 'Other')], default='NONE', max_length=16)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('payment_reference', models.CharField(blank=True, max_length=120)),
                ('payment_status', models.CharField(choices=[('NOT_REQUIRED', 'Not required'), ('GUEST_SENT', 'Guest says sent'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], db_index=True, default='NOT_REQUIRED', max_length=16)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('declared_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guest', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gift_declaration', to='guests.guest')),
                ('invitation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gift_declaration', to='invitations.invitation')),
                ('wedding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gift_declarations', to='weddings.wedding')),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['wedding', 'payment_status'], name='gift_wedding_status_idx')],
            },
        ),
    ]
