# Generated by Django 6.1.1 on 2026-09-13 17:56

import django.db.models.deletion
import gifts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0001_initial'),
        ('weddings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestgiftdeclaration',
            name='payment_method',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.CreateModel(
            name='GiftPaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_type', models.CharField(choices=[('PAY', 'Mobile Pay'), ('BANK', 'Bank Account')], max_length=12)),
                ('name', models.CharField(help_text='e.g. KBZPay, Wave Pay, AYA Bank', max_length=80)),
                ('account_name', models.CharField(max_length=120)),
                ('phone_number', models.CharField(blank=True, max_length=40)),
                ('account_number', models.CharField(blank=True, max_length=80)),
                ('qr_image', models.FileField(blank=True, upload_to=gifts.models.gift_qr_upload_to)),
                ('is_enabled', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wedding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gift_payment_methods', to='weddings.wedding')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='guestgiftdeclaration',
            name='payment_method_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='declarations', to='gifts.giftpaymentmethod'),
        ),
        migrations.AddConstraint(
            model_name='giftpaymentmethod',
            constraint=models.UniqueConstraint(fields=('wedding', 'name'), name='unique_gift_payment_method_name_per_wedding'),
        ),
    ]
