# Generated by Django 6.1.1 on 2026-09-13 17:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guests', '0001_initial'),
        ('invitations', '0001_initial'),
        ('weddings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RSVP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(choices=[('ATTENDING', 'Attending'), ('NOT_ATTENDING', 'Not attending'), ('MAYBE', 'Maybe')], db_index=True, max_length=20)),
                ('attending_adults', models.PositiveSmallIntegerField(default=0)),
                ('attending_children', models.PositiveSmallIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('responded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guest', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rsvp', to='guests.guest')),
                ('invitation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rsvp', to='invitations.invitation')),
                ('wedding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rsvps', to='weddings.wedding')),
            ],
            options={
                'ordering': ['-responded_at'],
                'indexes': [models.Index(fields=['wedding', 'response'], name='rsvp_wedding_response_idx')],
            },
        ),
    ]
