# Generated by Django 6.1.1 on 2026-09-13 16:11

import django.db.models.deletion
import invitations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guests', '0001_initial'),
        ('weddings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=invitations.models.generate_invitation_token, editable=False, max_length=100, unique=True)),
                ('qr_token', models.CharField(default=invitations.models.generate_qr_token, editable=False, max_length=100, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('READY', 'Ready'), ('SENT', 'Sent'), ('OPENED', 'Opened'), ('REVOKED', 'Revoked'), ('EXPIRED', 'Expired')], db_index=True, default='DRAFT', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('first_opened_at', models.DateTimeField(blank=True, null=True)),
                ('last_opened_at', models.DateTimeField(blank=True, null=True)),
                ('open_count', models.PositiveIntegerField(default=0)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guest', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invitation', to='guests.guest')),
                ('wedding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='weddings.wedding')),
            ],
        ),
    ]
