# Generated by Django 6.1.1 on 2026-09-13 17:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guests', '0001_initial'),
        ('invitations', '0001_initial'),
        ('weddings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_in_count', models.PositiveSmallIntegerField(default=0)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('return_gift_quantity', models.PositiveSmallIntegerField(default=0)),
                ('return_gift_issued_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checked_in_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wedding_checkins', to=settings.AUTH_USER_MODEL)),
                ('guest', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='checkin', to='guests.guest')),
                ('invitation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='checkin', to='invitations.invitation')),
                ('return_gift_issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_gift_issues', to=settings.AUTH_USER_MODEL)),
                ('wedding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='weddings.wedding')),
            ],
            options={
                'ordering': ['-checked_in_at', 'guest__name'],
                'indexes': [models.Index(fields=['wedding', 'checked_in_at'], name='checkin_wedding_time_idx')],
            },
        ),
    ]
